# RFM Analysis
From “big spenders” to “almost lost customers”, all customers have diverse needs and desires, and respond to your marketing campaigns in different ways.

As your business grows, segmenting your customers can significantly improve your marketing performance, making campaigns more relevant to more of your customers, ultimately increasing response rates and sales.

## What is RFM analysis?
RFM analysis is a customer segmentation technique that uses past purchase behavior to segment customers.

### RFM
* Recency (R) - Time since last purchase
* Frequency (F) - Total number of purchases
* Monetary value (M) - Total monetary value

RFM analysis was first used by the direct mail industry more than four decades ago, yet it is still an effective way to optimize your marketing.

Benefits of RFM analysis

* Increased customer retention
* Increased response rate
* Increased conversion rate
* Increased revenue

## Customer segmentation with RFM Analysis

To perform RFM analysis, we divide customers into four equal groups according to the distribution of values for recency, frequency, and monetary value.

Four equal groups across three variables create 64 (4x4x4) different customer segments, which is a manageable number.

Note that you can use quintiles (five equal groups) for increased granularity, but managing and acting on 125 segments (5x5x5) is significantly more challenging.
<pre>
Recency (R)	     Frequency (F)       Monetary Value (M)
Quartile 1 (R=1)	Quartile 1 (F=1)	Quartile 1 (M=1)
Quartile 2 (R=2)	Quartile 2 (F=2)	Quartile 2 (M=2)
Quartile 3 (R=3)	Quartile 3 (F=3)	Quartile 3 (M=3)
Quartile 4 (R=4)	Quartile 4 (F=4)	Quartile 4 (M=4)
</pre>
For example, let’s look at a customer who:

* is within the group who purchased most recently (R=1),
* is within the group who purchased most quantity (F=1),
* is within the group who spent the most (M=1)

This customer belongs to RFM segment 1-1-1 (Best Customers), (R=1, F=1, M=1)

Below is a table with key RFM segments:

<table style="text-align:left">
    <tr>
        <th style="text-align:left">Segment</th>
        <th style="text-align:left">RFM</th>
        <th style="text-align:left">Description</th>
        <th style="text-align:left">Marketing</th>
    </tr>
    <tr style="text-align:left">
        <td style="text-align:left">Best Customers</td>
        <td style="text-align:left">111</td>
        <td style="text-align:left">Customers who bought most recently, most often and spend the most</td>
        <td style="text-align:left">No price incentives, New Products and loyalty programs</td>
    </tr>
    <tr style="text-align:left">
        <td style="text-align:left">Loyal Customers</td>
        <td style="text-align:left">X1X</td>
        <td style="text-align:left">Customers who bought most recently</td>
        <td style="text-align:left">Use R and M to further segment</td>
    </tr>
    <tr style="text-align:left">
        <td style="text-align:left">Big Spenders</td>
        <td style="text-align:left">XX1</td>
        <td style="text-align:left">Customers who spend the most</td>
        <td style="text-align:left">Market your most expensive products</td>
    </tr>
    <tr style="text-align:left">
        <td style="text-align:left">Almost Lost</td>
        <td style="text-align:left">311</td>
        <td style="text-align:left">Haven't purchased for some time, but puchased frequently and spend the most</td>
        <td style="text-align:left">Agressive price incentives</td>
    </tr>
    <tr style="text-align:left">
        <td style="text-align:left">Lost Customers</td>
        <td style="text-align:left">411</td>
        <td style="text-align:left">Haven't purchased for some time, but puchased frequently and spend the most</td>
        <td style="text-align:left">Agressive price incentives</td>
    </tr>
    <tr style="text-align:left">
        <td style="text-align:left">Lost Cheap Customers</td>
        <td style="text-align:left">444</td>
        <td style="text-align:left">Last purchase long ago, purchased few and spend little</td>
        <td style="text-align:left">Don't spend too much trying to reacquire</td>
    </tr>
</table>

## How to Perform an RFM Analysis

Segmenting your customers database
To perform an RFM analysis you will need all the customer purchase history data. This is a file with all the transactions ever made by all of your customers.

## Interpreting the RFM Analysis
<table style="text-align:left">

<tr>
        <th style="text-align:left">Customer</th>
        <th style="text-align:left">Recency</th>
        <th style="text-align:left">Frequency</th>
        <th style="text-align:left">Monetary Value</th>
        <th style="text-align:left">RFM Class</th>
    </tr>
    <tr style="text-align:left">
        <td style="text-align:left">Etha K.</td>
        <td style="text-align:left">4 days</td>
        <td style="text-align:left">58 orders</td>
        <td style="text-align:left">&#36;2869</td>
        <td style="text-align:left">1-1-1</td>
    </tr>
    <tr style="text-align:left">
        <td style="text-align:left">Jerold Sporer</td>
        <td style="text-align:left">50 days</td>
        <td style="text-align:left">1 order</td>
        <td style="text-align:left">&#36;44</td>
        <td style="text-align:left">3-4-4</td>
    </tr>
    <tr style="text-align:left">
        <td style="text-align:left">Anie Hettinger</td>
        <td style="text-align:left">47 days</td>
        <td style="text-align:left">2 orders</td>
        <td style="text-align:left">&#36;156</td>
        <td style="text-align:left">3-2-1</td>
    </tr>
</table>

Etha K. belongs to the “Best Customers” segment; she purchased recently (R=1), frequently buys (F=1) and spent the most (M=1).

Jerold Sporer is about to enter the “Lost Cheap Customers” segment; he has not purchased in a while (R=3), bought few (F=4), and spent little (M=4).

Anie Hettinger is a type of “Almost Lost” customer. She has not made a purchase for some time (R=3), she bought somewhat frequently (F=2), but she is in the group who spent the most (M=1).

With these simple RFM analysis steps, you segmented your customer database. Now, create a team activity to browse through the RFM segments and identify which are important for your business.

Or, create a custom Tableau dashboard, like the RFM analysis dashboard below, to visualize your data.

In [1]:
import pyodbc
import pandas as pd
import datetime as dt
import warnings
warnings.filterwarnings('ignore')

In [2]:
sql_conn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server}; SERVER=localhost;DATABASE=AdventureWorksDW2019;UID=sa;PWD=SQLServer2019')

In [3]:
#Let's do a test to see if we can extract data
query = "select SalesOrderNumber, OrderDate,c.FirstName + ' ' + c.LastName Customer,SalesAmount from FactInternetSales f join DimCustomer c on f.CustomerKey=c.CustomerKey"
df_orders = pd.read_sql(query,sql_conn)
df_orders.head(3)

  SalesOrderNumber  OrderDate          Customer  SalesAmount
0          SO43697 2018-12-29       Cole Watson      3578.27
1          SO43698 2018-12-29  Rachael Martinez      3399.99
2          SO43699 2018-12-29     Sydney Wright      3399.99

In [4]:
anchor_date_sql = "select max(orderdate) anchor_date from factinternetsales"
anchor_date = pd.read_sql(anchor_date_sql,sql_conn)
anchor_date

  anchor_date
0  2022-01-28

Create RFM Table

In [5]:
import datetime as dt
NOW = dt.datetime(2022,1,28)
rfmtable = df_orders.groupby('Customer').agg({'OrderDate':lambda x:(NOW - x.max()).days, # Recency
                                              'SalesOrderNumber': lambda x: len(x),      # Frequency
                                              'SalesAmount': lambda x:x.sum()})          # Monetary
print(rfmtable)

                 OrderDate  SalesOrderNumber  SalesAmount
Customer
Aaron Adams            275                 4       117.96
Aaron Alexander         46                 1        69.99
Aaron Allen            788                 1      3399.99
Aaron Baker            141                 2      1750.98
Aaron Bryant           186                 5       133.96
...                    ...               ...          ...
Zoe Rogers              13                 2        39.98
Zoe Sanchez            195                 3        76.96
Zoe Sanders            135                 1         4.99
Zoe Torres             247                 2        14.98
Zoe Watson             160                 4        89.46

[18400 rows x 3 columns]

In [6]:
rfmtable['OrderDate'] = rfmtable['OrderDate'].astype(int)
rfmtable.rename(columns={'OrderDate':'recency',
                         'SalesOrderNumber':'frequency',
                         'SalesAmount':'monetary'},inplace=True)

## Validating the RFM table

In [7]:
rfmtable.head()

                 recency  frequency  monetary
Customer
Aaron Adams          275          4    117.96
Aaron Alexander       46          1     69.99
Aaron Allen          788          1   3399.99
Aaron Baker          141          2   1750.98
Aaron Bryant         186          5    133.96

## Determining RFM Quantiles

In [8]:
quantiles = rfmtable.quantile(q=[0.25,0.5,0.75])
quantiles

      recency  frequency   monetary
0.25     85.0        2.0    49.9700
0.50    167.0        3.0   287.4500
0.75    263.0        4.0  2517.3275

In [9]:
quantiles = quantiles.to_dict()

In [10]:
quantiles

{'recency': {0.25: 85.0, 0.5: 167.0, 0.75: 263.0},
 'frequency': {0.25: 2.0, 0.5: 3.0, 0.75: 4.0},
 'monetary': {0.25: 49.97, 0.5: 287.45, 0.75: 2517.3274999999994}}

## Creating the RFM Segmentation table

In [11]:
rfmSegmentation = rfmtable

In [12]:
# Arguments (x - values, p - recency, monetary, frequency, k - quantiles dictionary)
def RClass(x,p,d):
    if x < d[p][0.25]:
        return 1
    elif x <= d[p][0.5]:
        return 2
    elif x <= d[p][0.75]:
        return 3
    else:
        return 4

In [13]:
# Arguments (x - values, p - recency, monetary, frequency, k - quantiles dictionary)
def FMClass(x,p,d):
    if x < d[p][0.25]:
        return 4
    elif x <= d[p][0.5]:
        return 3
    elif x <= d[p][0.75]:
        return 2
    else:
        return 1

In [14]:
rfmSegmentation['R_Quartile'] = rfmSegmentation['recency'].apply(RClass,args=('recency',quantiles))
rfmSegmentation['F_Quartile'] = rfmSegmentation['frequency'].apply(FMClass,args=('frequency',quantiles))
rfmSegmentation['M_Quartile'] = rfmSegmentation['monetary'].apply(FMClass,args=('monetary',quantiles))
rfmSegmentation.head()

,recency,frequency,monetary,R_Quartile,F_Quartile,M_Quartile
Customer,,,,,,
Aaron Adams,275,4,117.96,4,2,3
Aaron Alexander,46,1,69.99,1,4,3
Aaron Allen,788,1,3399.99,4,4,1
Aaron Baker,141,2,1750.98,2,3,2
Aaron Bryant,186,5,133.96,3,1,3

In [15]:
rfmSegmentation['RFMClass'] = rfmSegmentation.R_Quartile.map(str) \
                            + rfmSegmentation.F_Quartile.map(str) \
                            + rfmSegmentation.M_Quartile.map(str)

rfmSegmentation.head()

,recency,frequency,monetary,R_Quartile,F_Quartile,M_Quartile,RFMClass
Customer,,,,,,,
Aaron Adams,275,4,117.96,4,2,3,423
Aaron Alexander,46,1,69.99,1,4,3,143
Aaron Allen,788,1,3399.99,4,4,1,441
Aaron Baker,141,2,1750.98,2,3,2,232
Aaron Bryant,186,5,133.96,3,1,3,313

In [16]:
rfmSegmentation[rfmSegmentation['RFMClass']=='111'].sort_values('monetary',ascending=False).head(5)

,recency,frequency,monetary,R_Quartile,F_Quartile,M_Quartile,RFMClass
Customer,,,,,,,
Jordan Turner,60,20,15999.0996,1,1,1,111
Willie Xu,69,9,13490.0596,1,1,1,111
Nichole Nara,69,13,13295.3800,1,1,1,111
Margaret He,70,14,13269.2700,1,1,1,111
Rosa Hu,68,15,13215.6500,1,1,1,111

## Output RFM score data

In [17]:
rfmSegmentation.to_csv('RFM-table.csv',sep=',')